from app.models.competency import Competency
from app.models.role import Role
from app.models.role_competency import RoleCompetency
from app.models.course import Course
from app.models.course_competency import CourseCompetency
from app.models.training_programme import TrainingProgramme
from app.models.training_competency import TrainingCompetency
from app.models.official import Official
from app.models.official_competency import OfficialCompetency
from app.models.learning_history import LearningHistory
from app.models.assessment import Assessment
from app.models.question import Question
from app.models.question_option import QuestionOption
from app.models.assessment_attempt import AssessmentAttempt