"""Create learning history table

Revision ID: 155d6df7af77
Revises: 7c4cc4be3979
Create Date: 2026-09-17 21:32:16.070337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155d6df7af77'
down_revision: Union[str, Sequence[str], None] = '7c4cc4be3979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_history',
    sa.Column('history_id', sa.String(length=20), nullable=False),
    sa.Column('official_id', sa.String(length=20), nullable=False),
    sa.Column('learning_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=20), nullable=False),
    sa.Column('resource_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['official_id'], ['officials.official_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_history')
    # ### end Alembic commands ###
