"""Create courses table

Revision ID: 49a6433f319c
Revises: 931e4334cf5b
Create Date: 2026-09-17 14:06:35.100561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a6433f319c'
down_revision: Union[str, Sequence[str], None] = '931e4334cf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('course_type', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('catalogue_source', sa.String(length=150), nullable=False),
    sa.Column('verification_status', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
