"""Add role to officials

Revision ID: 54c0a60bfdb2
Revises: 46cda3227666
Create Date: 2026-09-17 21:49:44.004795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c0a60bfdb2'
down_revision: Union[str, Sequence[str], None] = '46cda3227666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officials', sa.Column('role_id', sa.String(length=20), nullable=False))
    op.create_foreign_key(
    'fk_officials_role_id_roles',
    'officials',
    'roles',
    ['role_id'],
    ['role_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_officials_role_id_roles',
    'officials',
    type_='foreignkey'
    )
    op.drop_column('officials', 'role_id')
    # ### end Alembic commands ###
