"""Create assessment attempts table

Revision ID: 6128d4a0b9a2
Revises: 54c0a60bfdb2
Create Date: 2026-09-17 21:53:22.453306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6128d4a0b9a2'
down_revision: Union[str, Sequence[str], None] = '54c0a60bfdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempts',
    sa.Column('attempt_id', sa.String(length=20), nullable=False),
    sa.Column('assessment_id', sa.String(length=20), nullable=False),
    sa.Column('official_id', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['officials.official_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_attempts')
    # ### end Alembic commands ###
