"""Create official competencies table

Revision ID: 7c4cc4be3979
Revises: c06a59aca950
Create Date: 2026-09-17 21:20:13.760045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4cc4be3979'
down_revision: Union[str, Sequence[str], None] = 'c06a59aca950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_competencies',
    sa.Column('official_id', sa.String(length=20), nullable=False),
    sa.Column('competency_id', sa.String(length=20), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('assessment_source', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.competency_id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['officials.official_id'], ),
    sa.PrimaryKeyConstraint('official_id', 'competency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_competencies')
    # ### end Alembic commands ###
