"""Create roles table

Revision ID: 8030fbabb1fb
Revises: d2a1c36ed9ec
Create Date: 2026-09-17 13:58:01.243070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8030fbabb1fb'
down_revision: Union[str, Sequence[str], None] = 'd2a1c36ed9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('role_name', sa.String(length=150), nullable=False),
    sa.Column('role_type', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=200), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
