"""Create role competencies table

Revision ID: 931e4334cf5b
Revises: 8030fbabb1fb
Create Date: 2026-09-17 14:04:31.877436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931e4334cf5b'
down_revision: Union[str, Sequence[str], None] = '8030fbabb1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_competencies',
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('competency_id', sa.String(length=20), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('mapping_basis', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.competency_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'competency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_competencies')
    # ### end Alembic commands ###
