"""Create course competencies table

Revision ID: b09adc9854ae
Revises: 49a6433f319c
Create Date: 2026-09-17 14:08:24.993679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09adc9854ae'
down_revision: Union[str, Sequence[str], None] = '49a6433f319c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_competencies',
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('competency_id', sa.String(length=20), nullable=False),
    sa.Column('mapping_basis', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.competency_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'competency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_competencies')
    # ### end Alembic commands ###
