"""Create officials table

Revision ID: c06a59aca950
Revises: ccedadc0d8c0
Create Date: 2026-09-17 14:15:44.765367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c06a59aca950'
down_revision: Union[str, Sequence[str], None] = 'ccedadc0d8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officials',
    sa.Column('official_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=200), nullable=False),
    sa.Column('current_assignment', sa.Text(), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('previous_trainings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('official_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officials')
    # ### end Alembic commands ###
