"""Create training competencies table

Revision ID: ccedadc0d8c0
Revises: db5e4d5a289d
Create Date: 2026-09-17 14:12:38.200318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccedadc0d8c0'
down_revision: Union[str, Sequence[str], None] = 'db5e4d5a289d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_competencies',
    sa.Column('training_id', sa.String(length=20), nullable=False),
    sa.Column('competency_id', sa.String(length=20), nullable=False),
    sa.Column('relevance', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.competency_id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training_programmes.training_id'], ),
    sa.PrimaryKeyConstraint('training_id', 'competency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_competencies')
    # ### end Alembic commands ###
