"""Create training programmes table

Revision ID: db5e4d5a289d
Revises: b09adc9854ae
Create Date: 2026-09-17 14:11:05.278267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db5e4d5a289d'
down_revision: Union[str, Sequence[str], None] = 'b09adc9854ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_programmes',
    sa.Column('training_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('training_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_programmes')
    # ### end Alembic commands ###
